# Generated by Django 4.0.4 on 2022-05-20 19:00

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Назва буклету', max_length=200, verbose_name='Назва')),
                ('pdfvalue', models.FileField(blank=True, default='', help_text='.pdf', upload_to='booklets/%Y/%m/%d/', verbose_name='.PDF файл')),
            ],
            options={
                'verbose_name': 'Буклет',
                'verbose_name_plural': 'Буклети',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Категорія', max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, help_text='Коротка назва для url', max_length=200, unique=True, verbose_name='URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='dst.category', verbose_name='Головна категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='KoshtorisProektu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('name', models.CharField(db_index=True, help_text='Назва проекту', max_length=200, verbose_name='Назва')),
                ('proj_square', models.CharField(default=' м2', help_text='Площа', max_length=200, verbose_name="Площа об'єкту")),
                ('location', models.CharField(help_text="Де знаходиться об'єкт", max_length=200, verbose_name="Місце знаходження об'єкту")),
                ('customer', models.CharField(help_text='ПІБ замовника', max_length=200, verbose_name='Замовник')),
                ('company_descr', models.CharField(blank=True, help_text='Опис компанії', max_length=200, verbose_name='Опис компанії')),
                ('creators', models.CharField(blank=True, help_text='ПІБ Засновників', max_length=200, verbose_name='Засновники компанії')),
                ('performer', models.CharField(help_text='ПІБ виконавця', max_length=200, verbose_name='Виконавець')),
                ('notation', models.TextField(help_text='Примітки', verbose_name='Примітки')),
                ('title_pdf', models.FileField(blank=True, default='', help_text='.pdf', upload_to='static/', verbose_name='Титулка')),
            ],
            options={
                'verbose_name': 'Шаблон КП',
                'verbose_name_plural': 'Шаблони КП',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceOrProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Назва товару чи послуги', max_length=200, verbose_name='Назва')),
                ('image', models.ImageField(blank=True, help_text='фото', upload_to='productsimage/%Y/%m/%d/', verbose_name='Фото')),
                ('description', models.TextField(help_text='Опис товару чи послуги', verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, help_text='Ціна', max_digits=10, verbose_name='Ціна')),
                ('currencyrate', models.CharField(default='EUR', help_text='Виберіть валюту', max_length=3, verbose_name='Валюта')),
                ('slug', models.SlugField(blank=True, help_text='Коротка назва для url', max_length=200, unique=True, verbose_name='URL')),
                ('sale', models.BooleanField(default=False, verbose_name='Знижка')),
                ('connection_between', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceOrProducts', to='dst.category', verbose_name='Группа товару')),
            ],
            options={
                'verbose_name': 'Товар/Послуга',
                'verbose_name_plural': 'Товари/Послуги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PdfDescr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='.pdf', help_text='Назва файлу', max_length=200, verbose_name='Назва')),
                ('pdfvalue', models.FileField(blank=True, help_text='.pdf', upload_to='pdfdescr/%Y/%m/%d/', verbose_name='.PDF файл')),
                ('connection_between', models.OneToOneField(help_text="Зв'язати з товаром", on_delete=django.db.models.deletion.CASCADE, to='dst.serviceorproduct', verbose_name="Зв'язок з товаром")),
            ],
            options={
                'verbose_name': '.pdf файл продукту',
                'verbose_name_plural': '.pdf файли продуктів',
            },
        ),
    ]
