# Generated by Django 4.0.4 on 2022-05-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorproduct',
            name='currency_rate',
            field=models.CharField(choices=[('UAN', 'Гривня'), ('EUR', 'Євро'), ('USD', 'Доллар')], default='EUR', help_text='Виберіть валюту', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='koshtorisproektu',
            name='notation',
            field=models.TextField(blank=True, help_text='Примітки', verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='koshtorisproektu',
            name='proj_square',
            field=models.CharField(help_text='Площа м2', max_length=200, verbose_name="Площа об'єкту"),
        ),
        migrations.AlterField(
            model_name='serviceorproduct',
            name='currencyrate',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='serviceorproduct',
            name='image',
            field=models.ImageField(blank=True, help_text='фото', null=True, upload_to='productsimage/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
