# Generated by Django 4.0.4 on 2022-05-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dst', '0002_serviceorproduct_currency_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorproduct',
            name='currencyrate',
        ),
        migrations.AlterField(
            model_name='serviceorproduct',
            name='currency_rate',
            field=models.CharField(choices=[('UAN', 'UAN'), ('EUR', 'EUR'), ('USD', 'USD')], default='EUR', help_text='Виберіть валюту', max_length=3, verbose_name='Валюта'),
        ),
    ]
